### ISSUE TITLE
Build errors on simulator

### ISSUE THREAD

**Issue by TedCastillo** [snebragd/stringent#2]
I ran ./build.sh and I got two warning messages. I already turned it off ; //#define SERIAL_DEBUG but I still have problems:

In file included from sim.c:3:
In file included from /usr/include/stdio.h:27:
In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33:
/usr/include/features.h:184:3: warning: "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-W#warnings]
# warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
  ^
In file included from sim.c:173:
/tmp/data.ino:57:21: warning: too many arguments in call to 'makePenNoise'
      makePenNoise(3);
      ~~~~~~~~~~~~  ^
2 warnings generated.


I really don't have any idea what it could be.

**Comment by snebragd** [comment]
The first warning seems to have something to do with how libc is setup on your machine.

The second warning is my bad. I changed the real implementation of makePenNoise but forgot to update the mocked version in sim.c. 

I believe your compilation of the simulator will be successful anyway since there are just warnings. (I know this is a horrible thing to say, but this really is a dirty hack, eg. using sed to preprocess stuff...)

**Comment by TedCastillo** [comment]
Thank you. I will try it.

**Comment by TedCastillo** [comment]
Sorry It´s been a while. I have been busy but I have news. 

I can run the simulador putting "makePenNoise" as a  comment and adding the librery "#define _DEFAULT_SOURCE 1" and  "#define _BSD_SOURCE" in "sim.c"

 I set up the plotter too but I have a new problem, I got it in "serial monitor":

Setup
Disparity =-1
8CB92
9CB92
44B92
CB92
9CB92
Cal: 1Dis)77.96
Cal: Disp=-2147483648
C4B92
B92
Found: 1.svg
Found<path>!
Segments=821
Scale=-1612166.50
MLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL....

Do you have any idea? because I can move the plotter but when I press "1" to start the drawn It does'nt do anything.
